# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ContactManager(object):
    def setupUi(self, ContactManager):
        ContactManager.setObjectName("ContactManager")
        ContactManager.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(parent=ContactManager)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 400, 600))
        self.stackedWidget.setObjectName("stackedWidget")
        self.loginPage = QtWidgets.QWidget()
        self.loginPage.setObjectName("loginPage")
        self.labelLoginTitle = QtWidgets.QLabel(parent=self.loginPage)
        self.labelLoginTitle.setGeometry(QtCore.QRect(100, 50, 200, 30))
        self.labelLoginTitle.setObjectName("labelLoginTitle")
        self.usernameInput = QtWidgets.QLineEdit(parent=self.loginPage)
        self.usernameInput.setGeometry(QtCore.QRect(50, 100, 300, 40))
        self.usernameInput.setObjectName("usernameInput")
        self.passwordInput = QtWidgets.QLineEdit(parent=self.loginPage)
        self.passwordInput.setGeometry(QtCore.QRect(50, 160, 300, 40))
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.passwordInput.setObjectName("passwordInput")
        self.submitLoginButton = QtWidgets.QPushButton(parent=self.loginPage)
        self.submitLoginButton.setGeometry(QtCore.QRect(50, 220, 300, 40))
        self.submitLoginButton.setObjectName("submitLoginButton")
        self.signupButton = QtWidgets.QPushButton(parent=self.loginPage)
        self.signupButton.setGeometry(QtCore.QRect(50, 280, 300, 40))
        self.signupButton.setObjectName("signupButton")
        self.stackedWidget.addWidget(self.loginPage)
        self.signupPage = QtWidgets.QWidget()
        self.signupPage.setObjectName("signupPage")
        self.labelSignupTitle = QtWidgets.QLabel(parent=self.signupPage)
        self.labelSignupTitle.setGeometry(QtCore.QRect(100, 50, 200, 30))
        self.labelSignupTitle.setObjectName("labelSignupTitle")
        self.signupUsernameInput = QtWidgets.QLineEdit(parent=self.signupPage)
        self.signupUsernameInput.setGeometry(QtCore.QRect(50, 100, 300, 40))
        self.signupUsernameInput.setObjectName("signupUsernameInput")
        self.signupPasswordInput = QtWidgets.QLineEdit(parent=self.signupPage)
        self.signupPasswordInput.setGeometry(QtCore.QRect(50, 160, 300, 40))
        self.signupPasswordInput.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.signupPasswordInput.setObjectName("signupPasswordInput")
        self.submitSignupButton = QtWidgets.QPushButton(parent=self.signupPage)
        self.submitSignupButton.setGeometry(QtCore.QRect(50, 220, 300, 40))
        self.submitSignupButton.setObjectName("submitSignupButton")
        self.stackedWidget.addWidget(self.signupPage)
        self.contactsPage = QtWidgets.QWidget()
        self.contactsPage.setObjectName("contactsPage")
        self.contactsListWidget = QtWidgets.QListWidget(parent=self.contactsPage)
        self.contactsListWidget.setGeometry(QtCore.QRect(10, 10, 380, 300))
        self.contactsListWidget.setObjectName("contactsListWidget")
        self.nameInput = QtWidgets.QLineEdit(parent=self.contactsPage)
        self.nameInput.setGeometry(QtCore.QRect(10, 320, 380, 30))
        self.nameInput.setObjectName("nameInput")
        self.phoneInput = QtWidgets.QLineEdit(parent=self.contactsPage)
        self.phoneInput.setGeometry(QtCore.QRect(10, 360, 380, 30))
        self.phoneInput.setObjectName("phoneInput")
        self.addContactButton = QtWidgets.QPushButton(parent=self.contactsPage)
        self.addContactButton.setGeometry(QtCore.QRect(10, 400, 180, 40))
        self.addContactButton.setObjectName("addContactButton")
        self.deleteContactButton = QtWidgets.QPushButton(parent=self.contactsPage)
        self.deleteContactButton.setGeometry(QtCore.QRect(200, 400, 180, 40))
        self.deleteContactButton.setObjectName("deleteContactButton")
        self.stackedWidget.addWidget(self.contactsPage)
        ContactManager.setCentralWidget(self.centralwidget)

        self.retranslateUi(ContactManager)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ContactManager)

    def retranslateUi(self, ContactManager):
        _translate = QtCore.QCoreApplication.translate
        ContactManager.setWindowTitle(_translate("ContactManager", "Quản lý danh bạ"))
        self.labelLoginTitle.setText(_translate("ContactManager", "Đăng nhập"))
        self.usernameInput.setPlaceholderText(_translate("ContactManager", "Tên đăng nhập"))
        self.passwordInput.setPlaceholderText(_translate("ContactManager", "Mật khẩu"))
        self.submitLoginButton.setText(_translate("ContactManager", "Đăng nhập"))
        self.signupButton.setText(_translate("ContactManager", "Chưa có tài khoản? Đăng ký"))
        self.labelSignupTitle.setText(_translate("ContactManager", "Đăng ký"))
        self.signupUsernameInput.setPlaceholderText(_translate("ContactManager", "Tên đăng nhập"))
        self.signupPasswordInput.setPlaceholderText(_translate("ContactManager", "Mật khẩu"))
        self.submitSignupButton.setText(_translate("ContactManager", "Đăng ký"))
        self.nameInput.setPlaceholderText(_translate("ContactManager", "Tên"))
        self.phoneInput.setPlaceholderText(_translate("ContactManager", "Số điện thoại"))
        self.addContactButton.setText(_translate("ContactManager", "Thêm liên hệ"))
        self.deleteContactButton.setText(_translate("ContactManager", "Xóa liên hệ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ContactManager = QtWidgets.QMainWindow()
    ui = Ui_ContactManager()
    ui.setupUi(ContactManager)
    ContactManager.show()
    sys.exit(app.exec())
