# Form implementation generated from reading ui file 'lesson7_p1.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(parent=self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(50, 70, 600, 300))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans")
        font.setPointSize(10)
        self.listWidget.setFont(font)
        self.listWidget.setObjectName("listWidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 20, 300, 31))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal ExtraBold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(150, 400, 400, 35))
        font = QtGui.QFont()
        font.setFamily("Nunito Sans Normal")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.btn_search = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_search.setGeometry(QtCore.QRect(40, 470, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_search.setFont(font)
        self.btn_search.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 109, 51);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 93, 2);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.btn_search.setObjectName("btn_search")
        self.btn_edit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_edit.setGeometry(QtCore.QRect(370, 470, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_edit.setFont(font)
        self.btn_edit.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 109, 51);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 93, 2);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.btn_edit.setObjectName("btn_edit")
        self.btn_add = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_add.setGeometry(QtCore.QRect(200, 470, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_add.setFont(font)
        self.btn_add.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 109, 51);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 93, 2);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.btn_add.setObjectName("btn_add")
        self.btn_delete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(550, 470, 100, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_delete.setFont(font)
        self.btn_delete.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 109, 51);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(203, 93, 2);\n"
"    border: 2px solid black;\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"}")
        self.btn_delete.setObjectName("btn_delete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "List Widget"))
        self.btn_search.setText(_translate("MainWindow", "Search"))
        self.btn_edit.setText(_translate("MainWindow", "Edit"))
        self.btn_add.setText(_translate("MainWindow", "Add"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
