# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 635)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 10, 441, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color : white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, -30, 1011, 681))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/newPrefix/image/pixelcut-export.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.lstContacts = QtWidgets.QListWidget(parent=self.centralwidget)
        self.lstContacts.setGeometry(QtCore.QRect(40, 100, 431, 491))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lstContacts.setFont(font)
        self.lstContacts.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"padding-top:9px;")
        self.lstContacts.setObjectName("lstContacts")
        self.txtName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtName.setGeometry(QtCore.QRect(500, 110, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtName.setFont(font)
        self.txtName.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtName.setObjectName("txtName")
        self.txtPhone = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtPhone.setGeometry(QtCore.QRect(500, 180, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtPhone.setFont(font)
        self.txtPhone.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtPhone.setText("")
        self.txtPhone.setObjectName("txtPhone")
        self.txtEmail = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtEmail.setGeometry(QtCore.QRect(500, 250, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtEmail.setFont(font)
        self.txtEmail.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtEmail.setText("")
        self.txtEmail.setObjectName("txtEmail")
        self.txtAddress = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtAddress.setGeometry(QtCore.QRect(500, 320, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtAddress.setFont(font)
        self.txtAddress.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtAddress.setText("")
        self.txtAddress.setObjectName("txtAddress")
        self.btnEditContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEditContact.setGeometry(QtCore.QRect(500, 390, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnEditContact.setFont(font)
        self.btnEditContact.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 12pt \"Atkinson Hyperlegible Next\";\n"
"")
        self.btnEditContact.setObjectName("btnEditContact")
        self.btnDeleteContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnDeleteContact.setGeometry(QtCore.QRect(740, 390, 211, 51))
        self.btnDeleteContact.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 12pt \"Atkinson Hyperlegible Next\";\n"
"")
        self.btnDeleteContact.setObjectName("btnDeleteContact")
        self.btnLoadContacts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnLoadContacts.setGeometry(QtCore.QRect(500, 460, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnLoadContacts.setFont(font)
        self.btnLoadContacts.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 12pt \"Atkinson Hyperlegible Next\";\n"
"")
        self.btnLoadContacts.setObjectName("btnLoadContacts")
        self.btnSaveContacts = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSaveContacts.setGeometry(QtCore.QRect(740, 460, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnSaveContacts.setFont(font)
        self.btnSaveContacts.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 12pt \"Atkinson Hyperlegible Next\";\n"
"")
        self.btnSaveContacts.setObjectName("btnSaveContacts")
        self.btnAddContact = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnAddContact.setGeometry(QtCore.QRect(500, 530, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.btnAddContact.setFont(font)
        self.btnAddContact.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 12pt \"Atkinson Hyperlegible Next\";\n"
"")
        self.btnAddContact.setObjectName("btnAddContact")
        self.label_2.raise_()
        self.label.raise_()
        self.lstContacts.raise_()
        self.txtName.raise_()
        self.txtPhone.raise_()
        self.txtEmail.raise_()
        self.txtAddress.raise_()
        self.btnEditContact.raise_()
        self.btnDeleteContact.raise_()
        self.btnLoadContacts.raise_()
        self.btnSaveContacts.raise_()
        self.btnAddContact.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Contact Manager"))
        self.txtName.setPlaceholderText(_translate("MainWindow", "Name"))
        self.txtPhone.setPlaceholderText(_translate("MainWindow", "Phone Number"))
        self.txtEmail.setPlaceholderText(_translate("MainWindow", "Email "))
        self.txtAddress.setPlaceholderText(_translate("MainWindow", "Address"))
        self.btnEditContact.setText(_translate("MainWindow", "Edit Contact"))
        self.btnDeleteContact.setText(_translate("MainWindow", "Delete Contact"))
        self.btnLoadContacts.setText(_translate("MainWindow", "Load Contacts"))
        self.btnSaveContacts.setText(_translate("MainWindow", "Save Contacts"))
        self.btnAddContact.setText(_translate("MainWindow", "Add Contact"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
