# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(998, 635)
        LoginWindow.setMinimumSize(QtCore.QSize(998, 635))
        LoginWindow.setMaximumSize(QtCore.QSize(998, 635))
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-10, -10, 1011, 651))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/image/login.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.lb_login = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_login.setGeometry(QtCore.QRect(410, 80, 181, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(51)
        font.setBold(True)
        font.setWeight(75)
        self.lb_login.setFont(font)
        self.lb_login.setStyleSheet("color : white;")
        self.lb_login.setObjectName("lb_login")
        self.txtLUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLUsername.setGeometry(QtCore.QRect(270, 220, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtLUsername.setFont(font)
        self.txtLUsername.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtLUsername.setText("")
        self.txtLUsername.setObjectName("txtLUsername")
        self.txtLPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtLPass.setGeometry(QtCore.QRect(270, 300, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtLPass.setFont(font)
        self.txtLPass.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtLPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtLPass.setObjectName("txtLPass")
        self.pb_login = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_login.setGeometry(QtCore.QRect(420, 390, 151, 51))
        self.pb_login.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"\n"
"")
        self.pb_login.setObjectName("pb_login")
        LoginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.lb_login.setText(_translate("LoginWindow", "Login"))
        self.txtLUsername.setPlaceholderText(_translate("LoginWindow", "Insert Username"))
        self.txtLPass.setPlaceholderText(_translate("LoginWindow", "Insert Password"))
        self.pb_login.setText(_translate("LoginWindow", "Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LoginWindow = QtWidgets.QMainWindow()
    ui = Ui_LoginWindow()
    ui.setupUi(LoginWindow)
    LoginWindow.show()
    sys.exit(app.exec())
