# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegisterWindow(object):
    def setupUi(self, RegisterWindow):
        RegisterWindow.setObjectName("RegisterWindow")
        RegisterWindow.resize(998, 635)
        RegisterWindow.setMinimumSize(QtCore.QSize(998, 635))
        RegisterWindow.setMaximumSize(QtCore.QSize(998, 635))
        self.centralwidget = QtWidgets.QWidget(parent=RegisterWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_bg_Lg = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_bg_Lg.setGeometry(QtCore.QRect(0, -10, 1001, 651))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_bg_Lg.sizePolicy().hasHeightForWidth())
        self.lb_bg_Lg.setSizePolicy(sizePolicy)
        self.lb_bg_Lg.setText("")
        self.lb_bg_Lg.setPixmap(QtGui.QPixmap(":/newPrefix/image/signup.jpg"))
        self.lb_bg_Lg.setScaledContents(True)
        self.lb_bg_Lg.setObjectName("lb_bg_Lg")
        self.lb_register = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_register.setGeometry(QtCore.QRect(380, 70, 241, 81))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(46)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lb_register.setFont(font)
        self.lb_register.setStyleSheet("color : white;")
        self.lb_register.setObjectName("lb_register")
        self.txtSUsername = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSUsername.setGeometry(QtCore.QRect(270, 200, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtSUsername.setFont(font)
        self.txtSUsername.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtSUsername.setText("")
        self.txtSUsername.setObjectName("txtSUsername")
        self.txtSPass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtSPass.setGeometry(QtCore.QRect(270, 270, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtSPass.setFont(font)
        self.txtSPass.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtSPass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtSPass.setObjectName("txtSPass")
        self.txtCfpass = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.txtCfpass.setGeometry(QtCore.QRect(270, 340, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.txtCfpass.setFont(font)
        self.txtCfpass.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"padding-left:9px;\n"
"")
        self.txtCfpass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtCfpass.setObjectName("txtCfpass")
        self.pb_signup = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_signup.setGeometry(QtCore.QRect(410, 410, 151, 51))
        self.pb_signup.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"\n"
"")
        self.pb_signup.setObjectName("pb_signup")
        self.lb_register_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lb_register_2.setGeometry(QtCore.QRect(10, 600, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Atkinson Hyperlegible Next Extr")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lb_register_2.setFont(font)
        self.lb_register_2.setStyleSheet("color : white;")
        self.lb_register_2.setObjectName("lb_register_2")
        self.pb_signup_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pb_signup_2.setGeometry(QtCore.QRect(240, 590, 151, 41))
        self.pb_signup_2.setStyleSheet("background-color: rgba(8, 28, 75,0.4);\n"
"border: 3px solid white;\n"
"border-radius: 10px;\n"
"color:white;\n"
"font: 75 11pt \"Atkinson Hyperlegible Next\";\n"
"\n"
"")
        self.pb_signup_2.setObjectName("pb_signup_2")
        RegisterWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegisterWindow)
        QtCore.QMetaObject.connectSlotsByName(RegisterWindow)

    def retranslateUi(self, RegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        RegisterWindow.setWindowTitle(_translate("RegisterWindow", "MainWindow"))
        self.lb_register.setText(_translate("RegisterWindow", "Register"))
        self.txtSUsername.setPlaceholderText(_translate("RegisterWindow", "Insert Username"))
        self.txtSPass.setPlaceholderText(_translate("RegisterWindow", "Insert Password"))
        self.txtCfpass.setPlaceholderText(_translate("RegisterWindow", "Confirm Password"))
        self.pb_signup.setText(_translate("RegisterWindow", "Done"))
        self.lb_register_2.setText(_translate("RegisterWindow", "Already have an account?"))
        self.pb_signup_2.setText(_translate("RegisterWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RegisterWindow = QtWidgets.QMainWindow()
    ui = Ui_RegisterWindow()
    ui.setupUi(RegisterWindow)
    RegisterWindow.show()
    sys.exit(app.exec())
