# Form implementation generated from reading ui file 'doanso.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 800)
        MainWindow.setStyleSheet("background-color: rgba(215, 215, 217, 1);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(300, 70, 400, 120))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.goiy = QtWidgets.QLabel(parent=self.centralwidget)
        self.goiy.setGeometry(QtCore.QRect(225, 270, 550, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.goiy.setFont(font)
        self.goiy.setStyleSheet("background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.goiy.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.goiy.setObjectName("goiy")
        self.play_doanso = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.play_doanso.setGeometry(QtCore.QRect(150, 420, 700, 90))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.play_doanso.setFont(font)
        self.play_doanso.setStyleSheet("background-color: rgba(76, 100, 115, 0.5);")
        self.play_doanso.setInputMask("")
        self.play_doanso.setText("")
        self.play_doanso.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.play_doanso.setObjectName("play_doanso")
        self.check = QtWidgets.QPushButton(parent=self.centralwidget)
        self.check.setGeometry(QtCore.QRect(325, 570, 350, 70))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.check.setFont(font)
        self.check.setStyleSheet("background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.check.setObjectName("check")
        self.back_doanso = QtWidgets.QPushButton(parent=self.centralwidget)
        self.back_doanso.setGeometry(QtCore.QRect(40, 30, 121, 41))
        self.back_doanso.setStyleSheet("background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.back_doanso.setObjectName("back_doanso")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Đoán Số"))
        self.goiy.setText(_translate("MainWindow", "GỢI Ý Ở ĐÂY"))
        self.play_doanso.setPlaceholderText(_translate("MainWindow", "1-50"))
        self.check.setText(_translate("MainWindow", "CHECK"))
        self.back_doanso.setText(_translate("MainWindow", "BACK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
