# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgba(215, 215, 217, 1);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(175, 60, 650, 130))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.next_toan_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.next_toan_2.setGeometry(QtCore.QRect(550, 260, 371, 391))
        self.next_toan_2.setText("")
        self.next_toan_2.setPixmap(QtGui.QPixmap(":/image/image/toan.jfif"))
        self.next_toan_2.setScaledContents(True)
        self.next_toan_2.setObjectName("next_toan_2")
        self.label_doanso = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_doanso.setGeometry(QtCore.QRect(120, 260, 371, 391))
        self.label_doanso.setText("")
        self.label_doanso.setPixmap(QtGui.QPixmap(":/image/image/doanso.jfif"))
        self.label_doanso.setScaledContents(True)
        self.label_doanso.setObjectName("label_doanso")
        self.next_doanso = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_doanso.setGeometry(QtCore.QRect(200, 660, 191, 41))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.next_doanso.setFont(font)
        self.next_doanso.setStyleSheet("color: blue;\n"
"background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.next_doanso.setObjectName("next_doanso")
        self.next_toan = QtWidgets.QPushButton(parent=self.centralwidget)
        self.next_toan.setGeometry(QtCore.QRect(650, 660, 191, 41))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.next_toan.setFont(font)
        self.next_toan.setStyleSheet("color: blue;\n"
"background-color: rgba(217, 144, 102, 1);\n"
"border-radius: 20px;")
        self.next_toan.setObjectName("next_toan")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GAME"))
        self.next_doanso.setText(_translate("MainWindow", "PLAY"))
        self.next_toan.setText(_translate("MainWindow", "PLAY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
