# Form implementation generated from reading ui file 'zzui_dashboard.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Dashboard_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Dashboard_Label.setGeometry(QtCore.QRect(70, 30, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.Dashboard_Label.setFont(font)
        self.Dashboard_Label.setObjectName("Dashboard_Label")
        self.Roller_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Roller_Button.setGeometry(QtCore.QRect(50, 150, 75, 23))
        self.Roller_Button.setObjectName("Roller_Button")
        self.Slot_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Slot_Button.setGeometry(QtCore.QRect(50, 260, 75, 23))
        self.Slot_Button.setObjectName("Slot_Button")
        self.Switch_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Switch_Button.setGeometry(QtCore.QRect(220, 260, 75, 23))
        self.Switch_Button.setObjectName("Switch_Button")
        self.Money_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Money_Button.setGeometry(QtCore.QRect(220, 150, 80, 23))
        self.Money_Button.setObjectName("Money_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard"))
        self.Dashboard_Label.setText(_translate("MainWindow", "Dashboard"))
        self.Roller_Button.setText(_translate("MainWindow", "Roller"))
        self.Slot_Button.setText(_translate("MainWindow", "Slot Machine"))
        self.Switch_Button.setText(_translate("MainWindow", "Swap User"))
        self.Money_Button.setText(_translate("MainWindow", "Add Money"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
