# Form implementation generated from reading ui file 'regi.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Regi_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Regi_Button.setGeometry(QtCore.QRect(150, 310, 61, 21))
        self.Regi_Button.setObjectName("Regi_Button")
        self.Name_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_Line.setGeometry(QtCore.QRect(150, 137, 113, 20))
        self.Name_Line.setObjectName("Name_Line")
        self.Passw_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Passw_Line.setGeometry(QtCore.QRect(150, 167, 113, 20))
        self.Passw_Line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Passw_Line.setObjectName("Passw_Line")
        self.Conf_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Conf_Line.setGeometry(QtCore.QRect(150, 197, 113, 20))
        self.Conf_Line.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.Conf_Line.setObjectName("Conf_Line")
        self.Name_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_Label.setGeometry(QtCore.QRect(90, 140, 47, 13))
        self.Name_Label.setObjectName("Name_Label")
        self.Passw_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Passw_Label.setGeometry(QtCore.QRect(90, 170, 51, 16))
        self.Passw_Label.setObjectName("Passw_Label")
        self.Conf_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Conf_Label.setGeometry(QtCore.QRect(90, 200, 51, 16))
        self.Conf_Label.setObjectName("Conf_Label")
        self.Regi_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Regi_Label.setGeometry(QtCore.QRect(130, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.Regi_Label.setFont(font)
        self.Regi_Label.setObjectName("Regi_Label")
        self.Error_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Error_Label.setGeometry(QtCore.QRect(20, 270, 321, 16))
        self.Error_Label.setStyleSheet("color: rgb(255, 0, 0);")
        self.Error_Label.setText("")
        self.Error_Label.setObjectName("Error_Label")
        self.Switch_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Switch_Button.setGeometry(QtCore.QRect(270, 10, 75, 23))
        self.Switch_Button.setFlat(True)
        self.Switch_Button.setObjectName("Switch_Button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register"))
        self.Regi_Button.setText(_translate("MainWindow", "Register"))
        self.Name_Line.setPlaceholderText(_translate("MainWindow", "Enter name"))
        self.Passw_Line.setPlaceholderText(_translate("MainWindow", "Enter password"))
        self.Conf_Line.setPlaceholderText(_translate("MainWindow", "Confirm password"))
        self.Name_Label.setText(_translate("MainWindow", "Name:"))
        self.Passw_Label.setText(_translate("MainWindow", "Password:"))
        self.Conf_Label.setText(_translate("MainWindow", "Confirm:"))
        self.Regi_Label.setText(_translate("MainWindow", "Register"))
        self.Switch_Button.setText(_translate("MainWindow", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
