# Form implementation generated from reading ui file 'zzui_slotmachine.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 350)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Slotmachine_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Slotmachine_Label.setGeometry(QtCore.QRect(100, 40, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Slotmachine_Label.setFont(font)
        self.Slotmachine_Label.setObjectName("Slotmachine_Label")
        self.RTDB_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RTDB_Button.setGeometry(QtCore.QRect(240, 10, 111, 21))
        self.RTDB_Button.setFlat(True)
        self.RTDB_Button.setObjectName("RTDB_Button")
        self.Slot1_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Slot1_Line.setGeometry(QtCore.QRect(60, 120, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(75)
        self.Slot1_Line.setFont(font)
        self.Slot1_Line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Slot1_Line.setReadOnly(True)
        self.Slot1_Line.setObjectName("Slot1_Line")
        self.Slot2_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Slot2_Line.setGeometry(QtCore.QRect(140, 120, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(75)
        self.Slot2_Line.setFont(font)
        self.Slot2_Line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Slot2_Line.setReadOnly(True)
        self.Slot2_Line.setObjectName("Slot2_Line")
        self.Slot3_Line = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Slot3_Line.setGeometry(QtCore.QRect(220, 120, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(75)
        self.Slot3_Line.setFont(font)
        self.Slot3_Line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.Slot3_Line.setReadOnly(True)
        self.Slot3_Line.setObjectName("Slot3_Line")
        self.Roll_Button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Roll_Button.setGeometry(QtCore.QRect(130, 270, 91, 31))
        self.Roll_Button.setObjectName("Roll_Button")
        self.Earn_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.Earn_Label.setGeometry(QtCore.QRect(10, 310, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Earn_Label.setFont(font)
        self.Earn_Label.setStyleSheet("color: rgb(0, 177, 0);")
        self.Earn_Label.setObjectName("Earn_Label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Slot Machine"))
        self.Slotmachine_Label.setText(_translate("MainWindow", "Slot machine"))
        self.RTDB_Button.setText(_translate("MainWindow", "Return to dashboard"))
        self.Slot1_Line.setText(_translate("MainWindow", "1"))
        self.Slot2_Line.setText(_translate("MainWindow", "1"))
        self.Slot3_Line.setText(_translate("MainWindow", "1"))
        self.Roll_Button.setText(_translate("MainWindow", "Roll (25$)"))
        self.Earn_Label.setText(_translate("MainWindow", "Earn amount"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
